let employees=[
    {
        photo: null,
        firstName: 'John',
        lastName: 'Doe',
        dob: '1990-05-14',
        employeeId: 'E1001',
        email: 'john.doe@example.com',
        employeeType: 'Full-time',
        employeeStatus: 'Active',
        department: 'Engineering',
        city: 'New York',
        pin: '10001',
        pan: 'ABCDE1234F',
        salary: '80000',
        dateOfHire: '2020-06-15',
        employeeEndDate: ''
      },
      {
        photo: null,
        firstName: 'Jane',
        lastName: 'Smith',
        dob: '1988-09-22',
        employeeId: 'E1002',
        email: 'jane.smith@example.com',
        employeeType: 'Part-time',
        employeeStatus: 'Active',
        department: 'Marketing',
        city: 'Los Angeles',
        pin: '90001',
        pan: 'FGHIJ5678K',
        salary: '45000',
        dateOfHire: '2019-04-10',
        employeeEndDate: ''
      },
      {
        photo: null,
        firstName: 'Robert',
        lastName: 'Brown',
        dob: '1985-03-18',
        employeeId: 'E1003',
        email: 'robert.brown@example.com',
        employeeType: 'Contract',
        employeeStatus: 'Inactive',
        department: 'Finance',
        city: 'Chicago',
        pin: '60601',
        pan: 'KLMNO9876P',
        salary: '60000',
        dateOfHire: '2018-11-05',
        employeeEndDate: '2023-01-31'
      },
      {
        photo: null,
        firstName: 'Emily',
        lastName: 'Davis',
        dob: '1992-07-08',
        employeeId: 'E1004',
        email: 'emily.davis@example.com',
        employeeType: 'Full-time',
        employeeStatus: 'Active',
        department: 'HR',
        city: 'Houston',
        pin: '77001',
        pan: 'PQRST4321U',
        salary: '72000',
        dateOfHire: '2021-02-20',
        employeeEndDate: ''
      },
      {
        photo: null,
        firstName: 'Michael',
        lastName: 'Clark',
        dob: '1993-12-30',
        employeeId: 'E1005',
        email: 'michael.clark@example.com',
        employeeType: 'Intern',
        employeeStatus: 'Active',
        department: 'IT',
        city: 'Phoenix',
        pin: '85001',
        pan: 'UVWXY6543Z',
        salary: '30000',
        dateOfHire: '2023-06-01',
        employeeEndDate: ''
      },
      {
        photo: null,
        firstName: 'Sophia',
        lastName: 'Wilson',
        dob: '1987-01-25',
        employeeId: 'E1006',
        email: 'sophia.wilson@example.com',
        employeeType: 'Full-time',
        employeeStatus: 'Active',
        department: 'Sales',
        city: 'San Francisco',
        pin: '94101',
        pan: 'ABCDEF8765M',
        salary: '85000',
        dateOfHire: '2017-09-12',
        employeeEndDate: ''
      },
      {
        photo: null,
        firstName: 'Daniel',
        lastName: 'Martinez',
        dob: '1984-04-14',
        employeeId: 'E1007',
        email: 'daniel.martinez@example.com',
        employeeType: 'Part-time',
        employeeStatus: 'Inactive',
        department: 'Customer Support',
        city: 'San Diego',
        pin: '92101',
        pan: 'GHIJK3456N',
        salary: '40000',
        dateOfHire: '2016-07-08',
        employeeEndDate: '2022-12-31'
      },
      {
        photo: null,
        firstName: 'Olivia',
        lastName: 'Anderson',
        dob: '1995-06-19',
        employeeId: 'E1008',
        email: 'olivia.anderson@example.com',
        employeeType: 'Full-time',
        employeeStatus: 'Active',
        department: 'Legal',
        city: 'Austin',
        pin: '73301',
        pan: 'LMNOP2345Q',
        salary: '90000',
        dateOfHire: '2022-01-05',
        employeeEndDate: ''
      },
      {
        photo: null,
        firstName: 'William',
        lastName: 'Garcia',
        dob: '1989-02-11',
        employeeId: 'E1009',
        email: 'william.garcia@example.com',
        employeeType: 'Contract',
        employeeStatus: 'Active',
        department: 'Operations',
        city: 'Seattle',
        pin: '98101',
        pan: 'QRSTU1234V',
        salary: '70000',
        dateOfHire: '2015-05-20',
        employeeEndDate: ''
      },
      {
        photo: null,
        firstName: 'Charlotte',
        lastName: 'Harris',
        dob: '1998-11-23',
        employeeId: 'E1010',
        email: 'charlotte.harris@example.com',
        employeeType: 'Intern',
        employeeStatus: 'Active',
        department: 'Research',
        city: 'Denver',
        pin: '80201',
        pan: 'VWXYZ7890A',
        salary: '32000',
        dateOfHire: '2024-02-01',
        employeeEndDate: ''
      }
]


export default employees